[project]
scalaVersion       = "2.13.2"
#scalaJsVersion     = "0.6.32"  # requires nodejs installed (?).
#scalaNativeVersion = "0.3.9"   # llvm and clang stuff must be on the system. check the scala native site.

compilerDeps = [
    ["org.scalameta",              "semanticdb-scalac",        "4.3.10",    "full"],
    ["io.tryp",                    "splain",                   "0.5.5",     "full"],
    ["com.olegpy",                 "better-monadic-for",       "0.3.1"            ],
    ["org.typelevel",              "kind-projector",           "0.11.0",    "full"],
]
scalaOptions = [
    "-encoding", "UTF-8",
    "-unchecked",
    "-deprecation",
    "-feature",

    "-Yrangepos",
    "-Ywarn-numeric-widen",
    "-Ywarn-unused:imports",
    "-Ywarn-value-discard",
    "-Ywarn-dead-code",

    "-Xlint:adapted-args",
    "-Xlint:infer-any",
    "-Xlint:missing-interpolator",
    "-Xlint:private-shadow",
    "-Xlint:type-parameter-shadow",

    "-P:semanticdb:synthetics:on",
    "-P:semanticdb:failures:warning",
    "-P:semanticdb:sourceroot:/home/diaz/dev/personal/scala/ineninaru",
    "-P:semanticdb:targetroot:/home/diaz/dev/personal/scala/ineninaru/build/semanticdb",

    "-Xplugin-require:semanticdb",
]
testFrameworks = ["utest.runner.Framework"]


[module.server]
root = "."
moduleDeps = ["protocol"]
sources = ["src/server"]
targets = ["jvm"]
scalaDeps = [
    ["dev.zio",                       "zio",              "1.0.0-RC19-2"],
    ["dev.zio",                       "zio-interop-cats", "2.0.0.0-RC14"],
    ["dev.zio",                       "zio-streams",      "1.0.0-RC19-2"],
    ["dev.zio",                       "zio-nio",          "1.0.0-RC6"     ],
    ["com.softwaremill.sttp.client",  "core",             "2.1.1"     ],
    ["eu.timepit",                    "refined",          "0.9.14"    ],
    ["is.cir",                        "ciris",            "1.0.4"     ],
    ["io.scalaland",                  "chimney",          "0.5.1"     ],
    ["com.github.julien-truffaut",    "monocle-core",     "2.0.4"     ],
    ["com.propensive",                "magnolia",         "0.16.0"    ],
]

[module.server.test]
sources = ["test/server"]
scalaDeps = [
    ["com.lihaoyi", "utest", "0.7.4"]
]



[module.client]
root = "."
moduleDeps = ["protocol"]
sources = ["src/client"]
targets = ["jvm"]
scalaDeps = [
    ["dev.zio",                       "zio",            "1.0.0-RC19-2"],
    ["dev.zio",                       "zio-streams",    "1.0.0-RC19-2"],
    ["com.softwaremill.sttp.client",  "core",           "2.1.1"],
]

[module.client.test]
sources = ["test/client"]
scalaDeps = [
    ["com.lihaoyi", "utest", "0.7.4"]
]



[module.protocol]
root = "."
sources = ["src/protocol"]
targets = ["jvm"]

[module.protocol.test]
sources = ["test/protocol"]
scalaDeps = [
    ["com.lihaoyi", "utest", "0.7.4"]
]



