[project]
scalaVersion       = "2.13.1"
#scalaJsVersion     = "0.6.32"  # requires nodejs installed (?).
#scalaNativeVersion = "0.3.9"   # llvm and clang stuff must be on the system. check the scala native site.

# semanticdb is a compiler plugin that extracts details from the compiler
# and allows powerful tools like scalafix to work on those metadata.
compilerDeps = [
    ["org.scalameta",              "semanticdb-scalac",        "4.3.0",    "full"],
#    ["com.sksamuel.scapegoat",     "scalac-scapegoat-plugin",  "1.4.1",    "full"],
#    ["org.wartremove",             "wartremover",              "2.4.4",    "full"],
    ["io.tryp",                    "splain",                   "0.5.1",    "full"],
]
scalaOptions = [
    "-encoding", "UTF-8",
    "-unchecked",
    "-deprecation",
    "-feature",

    "-Ywarn-numeric-widen",
    "-Yrangepos",
    "-Ywarn-unused:imports",
    "-Ywarn-value-discard",
    "-Ywarn-dead-code",

    "-Xlint:adapted-args",
    "-Xlint:infer-any",
    "-Xlint:missing-interpolator",
    "-Xlint:private-shadow",
    "-Xlint:type-parameter-shadow",

#    "-P:scapegoat:dataDir:$BUILD_PATH/build/scapegoat",
#    "-P:wartremover:only-warn-traverser:org.wartremover.warts.Unsafe",
]
testFrameworks = ["utest.runner.Framework"]


[module.server]
root = "."
moduleDeps = ["protocol"]
sources = ["src/server"]
targets = ["jvm"]
scalaDeps = [
    ["dev.zio",                       "zio",              "1.0.0-RC17"],
    ["dev.zio",                       "zio-interop-cats", "2.0.0.0-RC10"],
    ["dev.zio",                       "zio-streams",      "1.0.0-RC17"],
    ["com.softwaremill.sttp.client",  "core",             "2.0.0-RC13"],
    ["eu.timepit",                    "refined",          "0.9.12"    ],
    ["is.cir",                        "ciris",            "1.0.4"     ],
    ["io.scalaland",                  "chimney",          "0.4.1"     ],
    ["com.github.julien-truffaut",    "monocle-core",     "2.0.0"     ],
    ["com.propensive",                "magnolia",         "0.12.6"    ],
]

[module.server.test]
sources = ["test/server"]
scalaDeps = [
    ["com.lihaoyi", "utest", "0.7.4"]
]



[module.client]
root = "."
moduleDeps = ["protocol"]
sources = ["src/client"]
targets = ["jvm"]
scalaDeps = [
    ["dev.zio",                       "zio",            "1.0.0-RC17"],
    ["dev.zio",                       "zio-streams",    "1.0.0-RC17"],
    ["com.softwaremill.sttp.client",  "core",           "2.0.0-RC13"],
]

[module.client.test]
sources = ["test/client"]
scalaDeps = [
    ["com.lihaoyi", "utest", "0.7.4"]
]



[module.protocol]
root = "."
sources = ["src/protocol"]
targets = ["jvm"]

[module.protocol.test]
sources = ["test/protocol"]
scalaDeps = [
    ["com.lihaoyi", "utest", "0.7.4"]
]



